//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaraokeManager.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderFoods = new HashSet<OrderFood>();
            this.OrderMusics = new HashSet<OrderMusic>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public string KaraokeType { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<double> RoomPrice { get; set; }
        public string Username { get; set; }
        public string RoomCode { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNumber { get; set; }
        public string PersonID { get; set; }
        public string Status { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderFood> OrderFoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderMusic> OrderMusics { get; set; }
    }
}
